### ISSUE TITLE
add stat boosts to game state

### ISSUE THREAD

**Issue by nickagliano** [nickagliano/bub#1]

**Comment by nickagliano** [comment]
with like stages and stuff. probably just an int, [-4, 4]

**Comment by SongSing** [comment]
tru.. there are also items/abilities that have modifiers outside of stat boosts (like guts).
so we could:
1. have boost stage and other mod for each stat
2. combine them and just have a total modifier for each stat
3. just apply the modifier to the stats directly, so if bub uses swords dance he will just see that the attack stat vry high

what u think

**Comment by SongSing** [comment]
going w/ applying directly for now
